### ISSUE TITLE
Slipping/Falling Over

### ISSUE THREAD

**Issue by TalkingCactus** [citadel-station/citadel-main#60]
Slipping can cause your pixel_y and rotation to flip out. You can replicate this by slipping while you're already downed or switch your run/walk intent while you're knocked down from a slip. I don't know if this happens from things like stunbatons.

It fixes itself when you change your run/walk intent after you've stood up. While silly, this is actually pretty confusing if you're in combat or what not.

Here's a few dead syndicate who were exposed to a slipping foam grenade. They ended up becoming upright and offset down a bit. The character on the right is alive after slipping and switching move intent before standing up.
![pic](http://image.prntscr.com/image/a764096852644ecfa3f8bb8cd82d8f5e.png)

**Comment by TalkingCactus** [comment]
bump

**Comment by TalkingCactus** [comment]
double bump

**Comment by LetterJay** [comment]
Was this in 5th?

**Comment by TalkingCactus** [comment]
6th

**Comment by LetterJay** [comment]
I can't find anything about the issue in the last few months on /tg/. Still trying to nail it down on it being the switching between Run/Walk or of it's slipping not locking your pixel_y

**Comment by Roland410** [comment]
Look for it in slipping, the run/walk thing is not the cause of it. I experienced it while on walk intent then slipped on lube. The run/walk switch didn't fix it either.

**Comment by LetterJay** [comment]
I've been looking into this. This doesn't happen in vanilla /tg/. So it's something that was tweaked in this build.

**Comment by Poojawa** [comment]
This was due to my trying to adjust Dogborg pixel locations. It went horribly. Check #54 line 817 of mob/living/living.dm Probably "fixed" due to overwrites

**Comment by Poojawa** [comment]
Likely fixed, except for edgecase soap cleaning?

**Comment by TalkingCactus** [comment]
fixed by what?

**Comment by Poojawa** [comment]
Most of the code that was involved being cleanly replaced. Unless it's still an issue?

**Comment by TalkingCactus** [comment]
Just tested this second on the live game, it is still an issue.
![proof](http://image.prntscr.com/image/91e5b2ec097e4918a8fbc2bd1768e027.png)
