### ISSUE TITLE
'Say' command stopped displaying speech

### ISSUE THREAD

**Issue by GlitchyCore** [citadel-station/citadel-main#662]
During a round that started about 1:30 server time today, things said using the 'say' command didn't show in the chat box, but things said over the radio still came through on their respective channels, and the 'whisper' command could still be used and would show up.

I don't think it was just a thing effecting me either, since other people were noticing it too.
![image](https://cloud.githubusercontent.com/assets/27295611/25562469/70636764-2d3b-11e7-8873-230238c240ab.png)
Here's showing that radio went through but local speech didn't, I was playing as Shay.
![image](https://cloud.githubusercontent.com/assets/27295611/25562508/2df77f5e-2d3c-11e7-82a9-4d0af2755d96.png)
And this is showing that 'whisper' could still be used.
![image](https://cloud.githubusercontent.com/assets/27295611/25562528/900ea79e-2d3c-11e7-8d04-dbeab27c7446.png)

**Comment by TalkingCactus** [comment]
Has this happened recently and can you confirm this is a bug with our code and not from /tg/?

**Comment by LetterJay** [comment]
I think this was fixed in #767

**Comment by GlitchyCore** [comment]
Happened again during a round starting about 4:00 server time today, same thing happening of 'say' not displaying locally, but radio and whispering still showed up.

**Comment by Poojawa** [comment]
This is likely fixed in #1490
